name: Python CI #what is name element? python workflow name

#Trigger the workflow on any push to the main branch or pull request
on: #define events when workflow wants to trigger. here push and pull to main branch, trigger the workflow
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - stage
      - qa

jobs:
  test:
    runs-on: ubuntu-latest #container creating for running actions we can also use windows or mac-os

    steps:
      # Step1: check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v2 #prebuild action

      # Step2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step3: Install dependencies
      - name: Install dependeincies
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step4: Run tests
      - name: Run test #it checks tests folder
        run: pytest
