name: Python CI #what is name element? python workflow name

#Trigger the workflow on any push to the main branch or pull request
on: #define events when workflow wants to trigger. here push and pull to main branch, trigger the workflow
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - stage
      - qa

jobs:
  unittesting:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        python-version: [ '3.9' ]
        os: [ ubuntu-latest ] #container creating for running actions we can also use windows or mac-os

    steps:
      # Step1: check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v2 #prebuild action

      # Step2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      # Step3: Install pip
      - name: Install pip
        run: python -m pip install --upgrade pip

      # Step4: Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Step3&4: Install pip & dependencies if we want to combine two commands use pipe symbol at run |
      # - name: Install dependencies
      #  run: |
       # python -m pip install --upgrade pip
       # pip install -r requirements.txt
          
      # Step5: Run tests
      - name: Run tests #it checks tests folder
        run: pytest
